name: plan-prd.yml
on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "tests/**/*"
      - "kanban/**/*"
      - ".claude/**/*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  plan-production:
    name: Plan Production
    uses: ./.github/workflows/deploy.yml
    with: 
      stageName: prd
    secrets: inherit
